# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c19cc9d1238343f30d0bc367a4f4768efd8c9809f9ef47256e712206dda0d86ea0a5adeea3f0a4f1514bc6ee36ab58554331acf0e71d31ab3a11369d65bb303

test:
  secret_key_base: a0fb54fe263d17639ed57d30191e1b038e4f9a27c34e0d2fbf310ff355c83ec7db6533bb53818632e25a75b88b53a09d19485ed779f6ab0d450082b2c8e79767

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
